### ISSUE TITLE
Xml feed problem?

### ISSUE THREAD

**Issue by cba85** [odan/odan.github.io#2]
Hello,

I follow your articles using [inoreader](https://www.inoreader.com/) and I just wanted to notify your XML feed seems to not work anymore 😞 

<img width="513" alt="Screenshot 2021-03-09 at 10 10 54" src="https://user-images.githubusercontent.com/720547/110446729-c8266380-80bf-11eb-85e9-f3ac07b2cd52.png">

Anyway, a big thank you for all your awesome articles!

**Comment by odan** [comment]
Hi @cba85 Thanks for the feedback.

I just tested it with QuiteRSS and Feedly without any problems.

![image](https://user-images.githubusercontent.com/781074/110462382-ea74ad00-80d0-11eb-9fe0-f47c4d2b91a0.png)

![image](https://user-images.githubusercontent.com/781074/110462478-07a97b80-80d1-11eb-84fa-8f0f8e985b09.png)

Have you tried to contact the inoreader support?

**Comment by odan** [comment]
The RSS feed should be fixed now. You can try it again. Thanks for following.

**Comment by cba85** [comment]
Thank you, it works again!! Thank you for the quick fix, and again, thank you for all your articles you have shared!
